Tests + configuration bugs worked out
lanl/BEE pull request #264
Opened 2020-11-10 16:06 UTC by rstyd

This PR adds a test suite for the WFM and TM.

2020-11-12 21:33 UTC, trandles-lanl requested changes
My comments in task_manager also apply to wfm

2020-11-30 16:18 UTC, pagrubel requested changes
To get the tests to work I moved the test directory into the beeflow directory and imported from beeflow.test.mocks

2020-12-08 17:23 UTC, trandles-lanl approved these changes
This looks good to me now.

One suggestion: Please add a couple lines to the test/readme.md file explaining how to run pytest against the new tests. An actual example command line would be nice.

2020-12-10 23:41 UTC, pagrubel approved these changes

2020-12-21 19:56 UTC, merged