Add UWSGI Support
lanl/BEE pull request #284
Opened 2021-01-28 02:16 UTC by rstyd

This PR addresses #151. Currently, there's an issue where cli.py starts the container more than once, and this causes the component sockets to be unavailable.

2021-01-28 18:10 UTC, qwofford reviewed
Looks good! It does seem like there might be some config template outputs that don't need to be in the repo, only a concern because there are hard-coded ports associated with @rstyd.

2021-02-11 22:42 UTC, pagrubel reviewed
beeflow --config-only no longer works

beeflow --config-only
Traceback (most recent call last):
  File "/yellow/users/pagrubel/BEE/BEE_Private/src/beeflow/cli.py", line 298, in StartNginx
    bc.userconfig['nginx']
  File "/usr/lib64/python3.6/configparser.py", line 959, in __getitem__
    raise KeyError(key)
KeyError: 'nginx'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/yellow/users/pagrubel/.cache/pypoetry/virtualenvs/beeflow-ApM-ipUD-py3.6/bin/beeflow", line 33, in <module>
    sys.exit(load_entry_point('beeflow', 'console_scripts', 'beeflow')())
  File "/yellow/users/pagrubel/BEE/BEE_Private/src/beeflow/cli.py", line 479, in main
    proc = StartNginx(bc, args)
  File "/yellow/users/pagrubel/BEE/BEE_Private/src/beeflow/cli.py", line 305, in StartNginx
    bc.modify_section('user','graphdb',graphdb_dict)
NameError: name 'graphdb_dict' is not defined

2021-02-16 23:49 UTC, pagrubel requested changes

2022-04-21 18:40 UTC, pagrubel commented
Should this PR be closed? @rstyd

2022-05-25 19:06 UTC, closed without merging