Requirements Refactor
lanl/BEE pull request #343
Opened 2021-06-15 23:14 UTC by Boogie3D

This PR makes the following changes:
* ~~Parser supports parsing of both hints and requirements~~
* `WorkflowInterface.create_requirement()` and `WorkflowInterface.create_hint()` now take two arguments
* `Requirement` and `Hint` classes now have two attributes: `class_` and `params`
  * `class_`: requirement class (`str`)
  * `params`: requirement parameters (`dict`)
* Neo4j now stores `Requirement` and `Hint` nodes with arbitrary properties instead of a single key-value pair
* Removed `BuildTask` from `wf_data.py`
* All tests in `test_wf_interface.py` are passing

Closes #341

2021-06-29 19:04 UTC, pagrubel reviewed
Needed some fixes so our current example will work.

2021-06-30 15:42 UTC, qwofford approved these changes
Works for the test case I use for workflow validation. Thanks @Boogie3D !

2021-06-30 19:09 UTC, qwofford requested changes
Let's revisit the Serious Python/PyPA and see if the CWL files in the parser2/ directory should be in src/beeflow/data.

2021-07-01 15:14 UTC, pagrubel approved these changes

2021-07-01 15:14 UTC, merged