Initial MPI Support
lanl/BEE pull request #412
Opened 2021-12-21 00:10 UTC by jtronge

This is an initial PR for adding MPI support with BEE. I've made a number of other changes as well and some of the code is not implemented in all of the workers, so I'm marking this initially as a WIP.

The main addition this adds is support for a new `beeflow:MPIRequirement` hint/requirement. Let me know if you think I should call it something different. To do this I've modified the Slurm worker code and some of the container runtime code to use `Command` objects when building the submission script.

You can take a look at the workflow in `src/beeflow/data/cwl/bee_workflows/comd-mpi` for an example of some parts of this requirement.

2021-12-21 00:14 UTC, jtronge commented on src/beeflow/common/config_driver.py
> +def BeeConfig(*pargs, **kwargs):
I think this should fix [Issue #405](https://github.com/lanl/BEE_Private/issues/405)

2022-02-01 19:57 UTC, jtronge commented on src/beeflow/data/cwl/bee_workflows/nwchem-mpi/README.md
> +## NWChem MPI Workflow
I added instructions for running this `nwchem-mpi` workflow in this README here.

2022-02-06 22:00 UTC, pagrubel commented
This should satisfy #426 .

2022-02-10 20:03 UTC, pagrubel commented
@jtronge So I believe these are the flags that will work for LSF (Summit):

[#jsrun](https://mattermost.energy.gov/beecharliecloud/messages/@jtronge#) -r 1 -c 1 
jsrun --rs_per_host 1 mkdir -p /var/tmp/<username>/beeflow_deployed_containers
jsrun --rs_per_host 1 ch-tar2dir <tarball>  /var/tmp/<username>/beeflow_deployed_containers

and for running there are many options so that should be flexible
I have a co worker that uses -n 256
but I'd say for the example that you had for nwchem it would be the following:

jsrun --rs_per_host 1 --tasks_per_rs 2 ch-run ...
jsrun -r 1 -c 1

2022-02-16 13:44 UTC, jtronge commented
I changed the CoMD workflow (in `src/beeflow/data/cwl/bee_workflows/comd-mpi/`) to be a multi-file workflow, so it should work with the parser. This example runs with 8 nodes, 1 task per node. The container file can be built with `ch-image build --force -f Dockerfile.comd-x86_64 -t comd .` from the `src/beeflow/data/dockerfiles` directory.

2022-03-29 14:48 UTC, jtronge commented
I'm thinking that to ensure that we can run jobs with many different possible options (MPI version, etc.) it might be better to put the script generation code into some sort of template. Putting all this logic in the worker code itself might not be the best option. I think I might try to make use of the existing template file code within the workers.

2022-03-29 14:56 UTC, pagrubel commented
I was going to eliminate the job template in favor of system settings for the #SBATCH or equivalent LSF directives. See issue #403

2022-03-29 17:58 UTC, jtronge commented
I wonder if we would be able to discuss this more at the meeting tomorrow? My original plan was to use a separate yaml file, similar to what CWL uses for their extension, but with more options. I'm realizing though, the problem with this set up is that it leads to more complex code in the workers (we have to add checks for each MPI requirement in each worker).
There are also other system-specific options that might need to be added on certain systems (for example the `--mpi=pmix_v3` that we needed for Darwin), and these would have to be added somehow to the worker code or to the command-line code.
This could also cause problems for when or if BEE eventually supports multiple task managers that each might work with a different resource manager.

So, instead, I'm wondering if it would be possible to generate a submission script using a system-specific template module that takes the commands generated by the container runtime, as well as specific hints/requirements as input. I believe this would allow for system-specific options to be taken into account, while still ensuring that workflows are reasonably portable between systems.

2022-03-29 18:15 UTC, jtronge commented
Here's an example of what I mean by a system-specific template module. This is using Jinja, which is what I also used in the cloud launching code, and is already a BEE dependency.

```
#!/bin/bash
#SBATCH --job-name={{ task_name }}-{{ task_id }}
#SBATCH --output={{ workflow_path }}/{{ task_name }}-{{ task_id }}.out
#SBATCH --error={{ workflow_path }}/{{ task_name }}-{{ task_id }}.err
{% if 'nodes' in task_info %}
#SBATCH -N {{ task_info['nodes'] }}
{% endif %}

{% for command in commands %}
{% if command.block is not none %}
{{ command.block }}
{% else %}
srun {{ command.argv|join(' ') }}
{% endif %}
{% endfor %}
```

2022-04-28 22:46 UTC, pagrubel commented
@jtronge This PR looks great and our basic example works fine. 
I was able to run mpi jobs on two different platforms using copyContainer, dockerFile with containerName and dockerPull. I'll probably add some dockerfiles that I need to build for darwin which has slurm with no pmix support. 

I especially like how you have moved some of the individual worker code into worker.py by using the jinja templates.   I still have some concern for users on managing jinja files especially in the future as we add more BEE CWL extensions.
Rusty and I went through the code together and have some questions for you, comments to follow.

2022-04-29 20:34 UTC, pagrubel requested changes

2022-04-29 20:34 UTC, pagrubel commented on src/beeflow/common/build_interfaces.py
> +    task = task.copy()
@jtronge can you explain why you are making a copy here? Would it be more understandable if the copy had a new name such as local_task

2022-04-29 20:34 UTC, pagrubel commented on src/beeflow/common/crt_drivers.py
> +                img = hints['DockerRequirement']['dockerImageId']
```suggestion
                img = hints['DockerRequirement']['copyContainer']
```

2022-04-29 20:34 UTC, pagrubel commented on src/beeflow/common/crt_drivers.py
> +            # I'm not sure if this should check for copyContainer here or not
```suggestion
```

2022-05-02 12:29 UTC, jtronge commented on src/beeflow/common/build_interfaces.py
> +    task = task.copy()
I made a copy here because the build driver is modifying the task object itself. Otherwise it affects other code in the task manager. I updated the name to be local_task

2022-05-02 12:30 UTC, jtronge commented on src/beeflow/common/crt_drivers.py
> +                img = hints['DockerRequirement']['dockerImageId']
I updated this. I just wasn't sure originally whether I should do that because I don't use the singularity driver

2022-05-02 12:40 UTC, jtronge commented
Thanks Pat. I think I made the changes. Let me know if you notice anything else.

2022-05-03 22:36 UTC, pagrubel commented
I added a working singularity example, although it is minimal.
I also added dockerfiles and instructions to build a container for the comd example with pmix support in the container. If slurm is not installed with pmix support the support needs to be in the container.

2022-05-03 22:56 UTC, rstyd commented on src/beeflow/common/build_interfaces.py
> +    local_task = task.copy()
I was wondering what exactly does this copy do? Is it just to prevent modifying the original task when we turn the hints and requirements into dictionaries?

2022-05-03 22:59 UTC, rstyd commented on src/beeflow/wf_manager.py
> +@flask_app.route('/bee_wfm/v1/status/<string:wf_id>')
What exactly is this route for? Looking at it I'm thinking it's part of the profiling, but I wanted to be sure.

2022-05-04 12:08 UTC, jtronge commented on src/beeflow/wf_manager.py
> +@flask_app.route('/bee_wfm/v1/status/<string:wf_id>')
I originally added this for the beeswarm client. Basically I used it to check for the status of a submitted workflow. I think there's another endpoint for this, `JobActions.get()` but it wasn't working for me. I can probably remove this for right now.

2022-05-04 12:26 UTC, jtronge commented on src/beeflow/common/build_interfaces.py
> +    local_task = task.copy()
Yeah, so to kind of give some background on this, when testing I was having a lot of trouble debugging the build driver. It seemed to fail arbitrarily and I realized that it was getting called through a `subprocess.run` call. A couple times I wasn't able to figure out what went wrong, because Charliecloud would fail or something else would happen. I think the log output and specific failures were just getting lost somehow.

I thought one way to possibly fix this issue was to invoke the build driver directly in Python, instead of using a `subprocess.run` call. That way the log would be inherited from the task manager, and we might be able to better note when errors occur. This change is in `src/beeflow/task_manager.py:160`. Basically I do a `from beeflow.common.build_interfaces import build_main` and then call build_main directly. I though this made sense since, at least for right now, the build interface seems to be a sort of sub-step or sub-component of the task manager.

Anyway, once I did that, I was able to get more output back from the build driver, but then I realized that it was modifying tasks in place. This is why I added the `task.copy()` function there, because otherwise it will mess with the other code in the task manager. There's definitely a better way to do this. I think we'll probably need to make some changes here in the future, but I'm just not overly familiar all of the code in the build driver yet.

Sorry for so much text, just thought my changes to the build interface needed a little more context.

2022-05-04 21:23 UTC, rstyd commented on src/beeflow/wf_manager.py
> +@flask_app.route('/bee_wfm/v1/status/<string:wf_id>')
Ah, okay yeah I've recently made some changes to that endpoint which will be brought in with the new CLI client PR.

2022-05-04 21:47 UTC, rstyd commented on src/beeflow/common/build_interfaces.py
> +    local_task = task.copy()
All the background info really helps so no need to apologize! That makes sense to me. I think the change of not using subprocess like that is good since it was a bit awkward. Might need a bit more refactoring around it in the future, but it's a solid change.

2022-05-04 21:48 UTC, rstyd commented
I approve!

2022-05-04 22:32 UTC, pagrubel approved these changes
Thanks for answering our questions Jake.

2022-05-04 22:32 UTC, merged