Add Build Integration Tests and Remove CLAMR
lanl/BEE pull request #526
Opened 2022-08-16 17:37 UTC by jtronge

This removes the CLAMR workflow from the integration tests, and adds in a number of different tests for the builder. This should test `beeflow:copyContainer`, `beeflow:useContainer`, `dockerFile` and `dockerPull`. Instead of relying on workflows in the `src/beeflow/data/` or `examples/` directories, the workflows and Dockerfiles are generated at test time from the code itself.

2022-08-16 17:41 UTC, jtronge commented
Also, you should be able to run this test locally (I ran it on darwin). After starting bee with `beeflow`, you should be able to run `./ci/integration_test.py`.

2022-08-16 18:05 UTC, pagrubel commented
Can you add that instruction in a Readme in the ci directory, if you haven't already

2022-08-16 18:39 UTC, jtronge commented
Ok I added the README.

2022-08-22 19:52 UTC, pagrubel commented
Probably should not use ch-image reset when running on a cluster. You could change it to ch-image delete and delete the images you created in the test

2022-08-22 20:36 UTC, pagrubel requested changes
Change ch-reset to ch-delete (specific images)

2022-08-23 18:22 UTC, pagrubel approved these changes

2022-08-23 18:36 UTC, pagrubel approved these changes

2022-08-23 18:37 UTC, merged