475 allow workflows from directories
lanl/BEE pull request #585
Opened 2022-11-06 19:15 UTC by aquan9

This PR allows you to do a bee_client submit and it will automatically do the packaging step if the workflow path is found to be a directory.

2022-11-06 19:17 UTC, aquan9 commented
My plan is to include the documentation updates in a separate PR since this one has such an old base.

2022-11-09 00:02 UTC, pagrubel requested changes
I'm thinking you should change the location of the tarball so that we don't have to do clean up.

2022-11-09 00:02 UTC, pagrubel commented on beeflow/client/bee_client.py
> +            wf_tarball = open(pathlib.Path("/tmp/" + str(wf_path.name) + ".tgz"), 'rb')
Why place the tarball in /tmp. I'd either like to see it placed in the working dir specified by the submit or cwd. Another option would be to put it in bee_workdir/workflows/<wf_id>/.  It ends up there anyway. Right now it is left in /tmp

2022-11-09 15:55 UTC, pagrubel commented on beeflow/client/bee_client.py
> +            wf_tarball = open(pathlib.Path("/tmp/" + str(wf_path.name) + ".tgz"), 'rb')
@aquan9 After thinking about this using /tmp is fine, if you remove the tar ball once the workflow is submitted

2022-11-09 19:28 UTC, jtronge commented
You might be able to use [tempfile.TemporaryDirectory](https://docs.python.org/3/library/tempfile.html#tempfile.TemporaryDirectory).

2022-11-10 22:28 UTC, aquan9 commented on beeflow/client/bee_client.py
> +            wf_tarball = open(pathlib.Path("/tmp/" + str(wf_path.name) + ".tgz"), 'rb')
I was able to get it to be stored in bee_workdir/archives where I found other tarballs. The wf_id doesn't appear to get generated until after the submission which is too late in the code. I also tried the tempfile idea, but there are too many places where the code might fail where the tmp dir might need to be cleaned up quickly before submission, so the cleanest thing to do seemed to put it in bee_workdir/archives or some other bee_workdir/<directory> if you prefer something else.

2022-11-10 23:01 UTC, aquan9 commented
I did a "git rebase develop" to pull in the documentation (and everything else that has happened in develop)

2022-11-10 23:42 UTC, pagrubel commented on beeflow/client/bee_client.py
> +            wf_tarball = open(pathlib.Path("/tmp/" + str(wf_path.name) + ".tgz"), 'rb')
Thanks looks good. We may want to change the example a bit in the future. I'm going to add CWL to the command section it is such a small change and should have been stated differently to begin.
This all look great! Thanks, @aquan9

2022-11-10 23:50 UTC, pagrubel approved these changes

2022-11-10 23:53 UTC, pagrubel requested changes
It seems the integration tests are failing

2022-11-14 23:53 UTC, pagrubel approved these changes
Looks good!

2022-11-14 23:54 UTC, merged