Remove delay time on workflow submit
lanl/BEE pull request #728
Opened 2023-10-02 14:31 UTC by jtronge

This should address issue #705. Tasks to start the GDB and initialize workflows are now offloaded to a celery backend based on Redis. I'm marking this as WIP since we still need to figure out the containers to use.

2023-10-04 20:43 UTC, jtronge commented
This adds a new config option `redis_image` for the Redis container. Right now it's just using the official one from docker hub.

2023-10-10 21:24 UTC, jtronge commented
The documentation for the new redis container should be updated now. I also changed `bee_dep_image` to `neo4j_image` in the config to be consistent.

2023-10-12 18:11 UTC, jtronge commented
I just added a command `beeflow core pull-deps` to download both the Neo4j and Redis containers. I think this should address #702.

2023-10-16 17:03 UTC, pagrubel requested changes
Should the command really be ``beeflow config pull-deps``?
Also, can you use the code that is used to load the charliecloud module if it doesn't exist to load it or warn that charliecloud is not available when using the command with the url for charliecloud, otherwise the user gets an error saying ch-image does not exist.
And the command to download the containers should also be documented in the command line interface section of either core or config wherever it ends up.

This probably should have been a separate pull request. I still need to review the rest of the pull request.

2023-10-16 17:58 UTC, pagrubel commented
I'm getting an error when I try to run the simple cat-grep-tar example on darwin. Attaching the error log. 
[bee-error-1697478790.log](https://github.com/lanl/BEE/files/12920306/bee-error-1697478790.log)

2023-10-16 19:00 UTC, pagrubel commented
> I'm getting an error when I try to run the simple cat-grep-tar example on darwin. Attaching the error log. [bee-error-1697478790.log](https://github.com/lanl/BEE/files/12920306/bee-error-1697478790.log)

Deleted my bee_workdir to have a clean copy and this cleared up the problem.

2023-10-16 20:10 UTC, rstyd commented on beeflow/client/core.py
> +        with open(os.path.join(paths.redis_root(), conf_name), 'w', encoding='utf-8') as fp:
I think we should only dump a config if one doesn't currently exist.

2023-10-16 22:01 UTC, rstyd commented on beeflow/wf_manager/resources/wf_actions.py
> +        if wf_utils.start_workflow(wf_id):
This is a great change!

2023-10-16 22:05 UTC, rstyd approved these changes
Everything looks great to me. I approve!

2023-10-17 16:17 UTC, pagrubel approved these changes
Thanks Jake this is great!

2023-10-17 16:17 UTC, merged