Add pre/post script support
lanl/BEE pull request #788
Opened 2024-02-26 23:30 UTC by rstyd

This PR addresses #773. It adds pre/post script support through a `beeflow:ScriptRequirement` hint which has the format:

```
    beeflow:ScriptRequirement:
    enabled: true
    pre_script_path: "pre_run.sh"
    post_script_path: "post_run.sh
```

The pre_run and post_run scripts are read using the parser and passed to the task object for the associated task. It's then read and added to the SBATCH script in the slurm runner.

2024-02-28 15:57 UTC, pagrubel commented
@rstyd Your example works. Please add it to all the workers and can you set up a test in CI? I think there should be a way to att it to the Flux and Slurm tests using a simpler example.

2024-02-28 15:58 UTC, pagrubel requested changes
As I commented it should be added to all the workers and if possible make CI tests.

2024-03-12 17:50 UTC, pagrubel commented
1. Add pre/post to all workers.
2. Add test to slurm and flux integration test.
3. Documentation.

2024-03-20 22:54 UTC, kchilleri submitted a review, later dismissed
Same pre/post script support will be added to the flux_worker (as requested by Pat) in a separate issue/PR. 
Test/documentation TBD?

2024-03-22 15:34 UTC, pagrubel commented
@kchilleri There may be some misunderstanding. Yes the flux implementation should be separate. However, this PR is still missing documentation and integration tests. So really it shouldn't be approved as is.

2024-03-22 17:02 UTC, kchilleri commented
@pagrubel Got it! Should I dismiss my approval?

2024-03-25 20:20 UTC, kchilleri submitted a review, later dismissed

2024-03-25 23:18 UTC, pagrubel approved these changes

2024-03-25 23:23 UTC, pagrubel requested changes
Thanks, @rstyd All looks good. Please squash the commits and let me know when you take out your debug Asserts.

2024-03-26 21:51 UTC, pagrubel requested changes

2024-03-26 21:51 UTC, pagrubel commented on docs/sphinx/bee_cwl.rst
> +and after a task. The script must be within the workflow directory.The shell
```suggestion
and after a task. The script must be within the workflow directory. The shell
```

2024-03-26 21:52 UTC, pagrubel approved these changes

2024-03-26 22:08 UTC, pagrubel commented
@rstyd Please squash the commits, or I can if you wish.

2024-03-26 23:03 UTC, merged