Export dag
lanl/BEE pull request #909
Opened 2024-08-28 14:52 UTC by Leahh02

This is my work from the visualize-day branch, but it's now coming off of develop.

The goal is to export a dag as a graphml so it can be used by visualization tool.

2024-08-28 14:53 UTC, Leahh02 commented
The changes in commit 2e284d15d945120efbe08fdd7cff140a104a325a is what made the "NOT_RESPONDING" state appear the other day. I'll test this again.

2024-08-28 15:06 UTC, Leahh02 commented
I tested it again and the "NOT_RESPONDING" state didn't appear.

2024-08-28 16:14 UTC, pagrubel commented
Thank you this is much easier to review.

2024-09-09 04:23 UTC, aquan9 requested changes, later dismissed
This is great work, thanks Leah.  

One last thing I'd like to see (besides the other changes I noted) before putting my final stamp of approval is an addition to our beeflow client documentation, since this change adds a new command to the client.

2024-09-09 04:23 UTC, aquan9 commented on generate_graph.py
> +    graphml_file = '/vast/home/leahh/.beeflow/dags/bebd6f.graphml'
Please remove this user specific path, and replace it with a generic path for this PR.

2024-09-09 04:23 UTC, aquan9 commented on generate_graph.py
I think it would also be better if we move this file inside of the gdb directory, inside of common. 

In otherwords .../beeflow/common/gdb/generate_graph.py

2024-09-09 22:45 UTC, pagrubel commented
@Leahh02 uses an augmented neo4j container for this capability. I'd like to see the Dockerfile for it in our repo to have a record of what to build. We will also need to fix the dependency build to use that, but that can be done in another PR.
I was able to verify that merging this would not affect running with the basic neo4j container. The dag functionality won't work but workflows will.

2024-09-11 21:19 UTC, Leahh02 commented
The clamr graph doesn't work, I'm trying to figure out why. I forgot to test it.

2024-09-11 21:50 UTC, Leahh02 commented
> The clamr graph doesn't work, I'm trying to figure out why. I forgot to test it.

I can create a dag when I have submitted the workflow with the no-start flag, but once I've started the workflow I can't make the graph anymore. The graphml file gets created but there's problems with networkx.

2024-09-16 19:17 UTC, pagrubel reviewed
This looks great! I made sure Andres's change requests were in this PR. I tested this and will run our local overnight tests, upon those passing I'll approve and merge.

2024-09-16 19:45 UTC, pagrubel approved these changes
Great job, thank you @Leahh02

2024-09-16 19:48 UTC, merged